#!/usr/bin/env python3
"""Generate the OFL-licensed Memory Bread 16x16 CJK bitmap font."""

import os
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "memory_bread/src/app/zh_font.h"
DEFAULT_FONT = ROOT / "tools/fonts/SourceHanSansCN-Regular.otf"
FONT = Path(os.environ.get("ZH_FONT", DEFAULT_FONT))
FONT_URL = (
    "https://raw.githubusercontent.com/adobe-fonts/source-han-sans/"
    "release/SubsetOTF/CN/SourceHanSansCN-Regular.otf"
)


def wanted_codepoints():
    # All characters in the Unicode CJK Unified Ideographs basic block.
    # ASCII letters, digits and punctuation are rendered by the Adafruit font.
    points = set(range(0x4E00, 0xA000))
    # Common Chinese punctuation used by the UI, ASR and LLM output.
    points.update(ord(ch) for ch in "、—…“”‘’·￥【】（）《》！？：；，。")
    return sorted(points)


def bitmap(font, ch):
    canvas = Image.new("L", (16, 16), 0)
    draw = ImageDraw.Draw(canvas)
    box = draw.textbbox((0, 0), ch, font=font)
    w, h = box[2] - box[0], box[3] - box[1]
    x = (16 - w) // 2 - box[0]
    y = (16 - h) // 2 - box[1]
    draw.text((x, y), ch, fill=255, font=font)
    pixels = canvas.load()
    rows = []
    for yy in range(16):
        for byte_x in range(2):
            value = 0
            for bit in range(8):
                if pixels[byte_x * 8 + bit, yy] >= 96:
                    value |= 1 << (7 - bit)
            rows.append(value)
    return rows


def main():
    if not FONT.exists():
        raise SystemExit(
            f"font not found: {FONT}\n"
            f"Download the official OFL font from:\n{FONT_URL}\n"
            "Then save it at the path above or set ZH_FONT=/path/to/font.otf."
        )

    font = ImageFont.truetype(str(FONT), 16, index=0)
    missing_glyph = bitmap(font, "\U0010ffff")
    wanted = wanted_codepoints()
    points = [cp for cp in wanted if bitmap(font, chr(cp)) != missing_glyph]
    point_set = set(points)
    skipped = [cp for cp in wanted if cp not in point_set]
    lines = [
        "// Memory Bread CJK Bitmap, generated by tools/generate_zh_font.py.",
        "// Derived from Source Han Sans CN Regular (Adobe), SIL OFL 1.1.",
        "// See licenses/OFL-1.1.txt. Do not edit this generated file manually.",
        "#pragma once",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        f"static constexpr uint16_t ZH_GLYPH_COUNT = {len(points)};",
        "static const uint16_t ZH_CODEPOINTS[ZH_GLYPH_COUNT] PROGMEM = {",
    ]
    for i in range(0, len(points), 16):
        lines.append("  " + ", ".join(f"0x{cp:04X}" for cp in points[i:i + 16]) + ",")
    lines.extend(["};", "", "static const uint8_t ZH_BITMAPS[ZH_GLYPH_COUNT][32] PROGMEM = {"])
    for cp in points:
        data = bitmap(font, chr(cp))
        lines.append("  {" + ",".join(f"0x{x:02X}" for x in data) + f"}}, // U+{cp:04X}")
    lines.extend(["};", ""])
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} with {len(points)} glyphs")
    if skipped:
        print("skipped unsupported codepoints: " +
              " ".join(f"U+{cp:04X}" for cp in skipped))


if __name__ == "__main__":
    main()
